name: Build the 24.04 Docker image

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Setup QEMU
        id: qemu
        uses: docker/setup-qemu-action@v4
        with:
          platforms: linux/amd64,linux/arm64,linux/armhf

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v7
        with:
          platforms: linux/amd64,linux/arm64,linux/armhf
          push: true
          file: dockerfiles/noble/Dockerfile
          tags: mahdisharifithedev/ubuntu-rust:24.04,mahdisharifithedev/ubuntu-rust:24.04-1.96,mahdisharifithedev/ubuntu-rust:24.04-latest,mahdisharifithedev/ubuntu-rust:noble,mahdisharifithedev/ubuntu-rust:noble-1.96,mahdisharifithedev/ubuntu-rust:noble-latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
      - name: Update dockerhub description
        uses: peter-evans/dockerhub-description@v5
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
          repository: mahdisharifithedev/ubuntu-rust
